"""The machine-readable export — one document, two consumers (ROADMAP contract 2).

SPEC §16: "keep a single shared JSON-schema module used by both server
validation and the client." This builds that document out of the same registry
:mod:`apps.flows.schema.validation` validates against, so the React config
panels (L3-C) and the server cannot describe different nodes.

**Deterministic on purpose.** The artefact is committed at
``static/flows/flow-schema.json`` and the build regenerates it, so byte-for-byte
stability is what makes "the committed file is stale" a diff instead of a
mystery: keys are sorted, no timestamp or version stamp is emitted, and every
list in the document comes from a literal or from registry insertion order.
``apps/flows/tests/test_export.py`` regenerates and compares, which turns drift
into a failing test in the suite CI already runs.

Alongside the schema proper, ``x-brightbean`` carries what a *builder* needs and
a validator does not: each node type's label, its palette group, its handles,
and the graph limits.
It is an extension keyword, so any other JSON-Schema consumer ignores it, and it
means L3-C reads one file rather than one file plus a hard-coded table.
"""

import copy
import json
from pathlib import Path
from typing import Any

from apps.flows.schema import fields as f
from apps.flows.schema.envelope import ID_PATTERN, MAX_EDGES, MAX_NODES, SCHEMA_VERSION, limits
from apps.flows.schema.handles import HANDLE_PATTERN
from apps.flows.schema.nodes import GROUPS, NODE_TYPES, all_defs

__all__ = ["ARTIFACT_RELATIVE_PATH", "artifact_path", "json_schema", "serialize"]

#: Where the generated artefact lives, relative to the repository root. Under
#: ``static/`` so it is served by the staticfiles finders and reachable from
#: ``{% static %}``, and so L3-C's bundler can import it from a stable path.
ARTIFACT_RELATIVE_PATH = Path("static") / "flows" / "flow-schema.json"

_SCHEMA_URI = "https://json-schema.org/draft/2020-12/schema"
_DOCUMENT_ID = "https://brightbean.chat/schemas/flow-graph-v1.json"


def artifact_path() -> Path:
    """Absolute path of the committed artefact."""
    from django.conf import settings

    return Path(settings.BASE_DIR) / ARTIFACT_RELATIVE_PATH


def json_schema() -> dict[str, Any]:
    """The whole graph format as one JSON-Schema document.

    The result is a **deep copy**. ``all_defs()`` hands back a shallow one, and
    the node configs come straight off the registry, so without this every
    fragment of the returned document would be the same object
    :func:`~apps.flows.schema.envelope.validate_document` validates against —
    and the first caller to adjust one for its own rendering would silently
    rewrite the rules the server enforces, for the life of the worker process.
    """
    defs = all_defs()
    defs["position"] = f.obj(
        {"x": {"type": "number"}, "y": {"type": "number"}},
        required=["x", "y"],
        description="Canvas coordinates. Builder state, ignored at runtime.",
    )

    for node_type, spec in NODE_TYPES.items():
        defs[f"node_{node_type}"] = f.obj(
            {
                "id": f.string(min_length=1, max_length=64, pattern=ID_PATTERN),
                "type": f.const(node_type),
                "position": f.ref("position"),
                "config": spec.config,
            },
            required=["id", "type", "position", "config"],
            description=spec.description,
        )

    defs["node"] = f.tagged_union("type", {node_type: f"node_{node_type}" for node_type in NODE_TYPES})
    defs["edge"] = f.obj(
        {
            # The same grammars validate_document enforces, not a prose
            # approximation of them: a document that accepts ids this server
            # refuses is a builder that generates graphs its own autosave
            # rejects.
            "id": f.string(min_length=1, max_length=64, pattern=ID_PATTERN),
            "source": f.string(min_length=1, max_length=64, pattern=ID_PATTERN),
            "sourceHandle": f.string(
                min_length=1,
                max_length=70,
                pattern=HANDLE_PATTERN,
                description="default | btn:<id> | qr:<id> | cond:true | cond:false | follow:<status> | rand:<id> | timeout | error",
            ),
            "target": f.string(min_length=1, max_length=64, pattern=ID_PATTERN),
        },
        required=["id", "source", "sourceHandle", "target"],
    )

    document = {
        "$schema": _SCHEMA_URI,
        "$id": _DOCUMENT_ID,
        "title": "BrightBean Chat flow graph",
        "description": (
            "Generated by apps/flows/schema/export.py — do not edit by hand. "
            "Run `make schema` (or `python manage.py export_flow_schema`) after changing the registry."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": ["schema", "nodes", "edges"],
        "properties": {
            "schema": {"type": "integer", "const": SCHEMA_VERSION},
            "nodes": f.array(f.ref("node"), max_items=MAX_NODES),
            "edges": f.array(f.ref("edge"), max_items=MAX_EDGES),
        },
        "x-brightbean": {
            "schema_version": SCHEMA_VERSION,
            "limits": limits(),
            # The palette drawers, ordered. Shipping the order and the labels as
            # data — rather than only the group key on each node type — is what
            # lets the builder render a drawer it has never heard of.
            "groups": [{"key": key, "label": label} for key, label in GROUPS],
            "node_types": [
                {
                    "type": spec.type,
                    "label": spec.label,
                    "description": spec.description,
                    "group": spec.group,
                    "handles": list(spec.handles),
                    "dynamic_handles": [
                        {"prefix": prefix, "config_key": config_key} for prefix, config_key in spec.dynamic_handles
                    ],
                    "terminal": spec.terminal,
                    "annotation": spec.annotation,
                }
                for spec in NODE_TYPES.values()
            ],
        },
        "$defs": defs,
    }
    return copy.deepcopy(document)


def serialize() -> str:
    """The artefact's exact bytes, as text."""
    return json.dumps(json_schema(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"
